# Generated by Django 4.2.9 on 2024-02-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='update_time',
        ),
    ]
