# Generated by Django 4.2.9 on 2024-02-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.CharField(db_comment='标签', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(db_comment='文章内容'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='headline',
            field=models.CharField(db_comment='文章标题', max_length=50),
        ),
        migrations.AlterField(
            model_name='articles',
            name='read_count',
            field=models.IntegerField(db_comment='阅读次数', default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='recommended',
            field=models.BooleanField(db_comment='是否收藏', default=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='reply_count',
            field=models.IntegerField(db_comment='评论数', default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='thumbnail',
            field=models.ImageField(db_comment='缩略图', upload_to=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='type',
            field=models.CharField(db_comment='文章类型', max_length=10),
        ),
    ]
